# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Your awesome title
  fr: Votre titre génial
email: your-email@domain.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://multilingual-sylvain.netlify.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Where things are

# Collections
collections:
  lorem-ipsum-project-en:
    type: "section"
  lorem-ipsum-project-fr:
    type: "section"


# Site defaults frontmatters
defaults:
  -
    scope:
      path: "/" # an empty string here means all files in the project
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout
      title: "jekyll page"
      permalink:
      ref: ref
      lang: en
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Mr. Hyde"
      title: "jekyll post"
      ref: ref
      date: 2016-02-29 09:48:44 +0100
      categories: jekyll update
      lang: en
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "section"
    values:
      order: 1
      include: projecte/hero.html
      titol_seccio: "Projecte"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
